# Generated by Django 5.1.2 on 2025-05-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='cart',
            name='diamond_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customizedproduct',
            name='diamond_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='diamond_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
