# Generated by Django 5.2.2 on 2025-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cart_diamond_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('accepted', 'accepted')], default='pending', max_length=20),
        ),
    ]
